const MSGS = {
  'USER_ADD': 'USER_ADDED_SUCCESSFUL',
  'USER_UPDATE': 'USER_UPDATE_SUCCESSFUL',
  'USER_DELETE': 'USER_DELETE_SUCCESSFUL',  
  'USER_ALREADY_EXIST':'USER_ALREADY_EXIST',
  'USER_ID_NOT_EXISTS':'USER_ID_NOT_EXISTS',
  'USER_MAPPED':'USER_MAPPED_PRODUCT',    
  'FEATURE_USER_UPDATE' : 'FEATURE_USER_UPDATE_SUCCESSFUL',
  'USER_ACTIVATE': 'USER_ACTIVATE',
  'USER_DEACTIVATE': 'USER_DEACTIVATE',
  'USER_FAIL': 'USER_FAILED'    
}

export {
  MSGS
};